// Generates the iOS String Catalogs used by the widget extension and the
// App Shortcuts provider, sourced from lib/l10n/app_*.arb.
//
// Why this exists: the widget extension and AppIntents are a *second*
// localization surface. `LocalizedStringResource` / `AppShortcut` phrases
// resolve through `.xcstrings` in their own target and cannot read the ARB
// catalogue. Rather than maintain 24 locales twice, this projects the relevant
// ARB keys into the two catalogs.
//
// Most *rendered* widget text is shipped pre-localized inside the snapshot
// JSON, so these catalogs stay small: configuration-sheet UI, Siri phrases,
// the widget-gallery entries, and the no-snapshot empty state (which must
// render before any snapshot exists).
//
// Run from the repo root:  dart run tool/gen_ios_widget_strings.dart

import 'dart:convert';
import 'dart:io';

/// iOS string-catalog key -> ARB key.
const Map<String, String> _widgetKeys = {
  'metric.type': 'widgetConfigMetric',
  'metric.spendable': 'heroBalance',
  'metric.networth': 'heroNet',
  'metric.lowest': 'widgetLowestPoint',
  'metric.projected': 'widgetProjected',
  'metric.account': 'widgetMetricAccount',
  'horizon.type': 'widgetConfigHorizon',
  'horizon.today': 'dateToday',
  'horizon.7d': 'widgetHorizonIn7Days',
  'horizon.eom': 'widgetHorizonEndOfMonth',
  'entity.account': 'selectAccount',
  'config.title': 'widgetNameNumbers',
  'config.desc': 'widgetDescNumbers',
  'config.metric': 'widgetConfigMetric',
  'config.account': 'selectAccount',
  'config.horizon': 'widgetConfigHorizon',
  'widget.numbers.name': 'widgetNameNumbers',
  'widget.numbers.desc': 'widgetDescNumbers',
  'widget.quickadd.name': 'widgetQuickAdd',
  'widget.quickadd.desc': 'widgetDescQuickAdd',
  'quickadd.tracked': 'emptyAddTransaction',
  'quickadd.planned': 'planAddPlan',
  'empty.title': 'emptyNoAccountsYet',
  'control.addTracked': 'emptyAddTransaction',
  'control.addTracked.desc': 'widgetDescQuickAdd',
  'control.addPlanned': 'planAddPlan',
  'control.addPlanned.desc': 'widgetDescQuickAdd',
  'intent.addTracked.title': 'emptyAddTransaction',
  'intent.addTracked.desc': 'widgetDescQuickAdd',
  'intent.addPlanned.title': 'planAddPlan',
  'intent.addPlanned.desc': 'widgetDescQuickAdd',
};

/// Compact-number suffixes have no ARB equivalent (they exist only in the
/// widget's circular accessory). Kept here rather than polluting the app's
/// catalogue with strings the app never shows.
const Map<String, Map<String, String>> _literals = {
  'unit.thousand': {'*': 'k'},
  'unit.million': {'*': 'M'},
};

/// Siri phrases. The `{appName}` placeholder in the ARB becomes the
/// `\${applicationName}` token the App Intents runtime substitutes.
const Map<String, String> _phraseKeys = {
  'Add a transaction in \${applicationName}': 'widgetSiriAddTransaction',
  'Add a planned transaction in \${applicationName}': 'widgetSiriAddPlanned',
};

/// ARB locale -> Xcode language id.
const Map<String, String> _localeMap = {
  'en': 'en',
  'es': 'es',
  'fr': 'fr',
  'de': 'de',
  'pt_BR': 'pt-BR',
  'pt': 'pt-PT',
  'it': 'it',
  'ru': 'ru',
  'pl': 'pl',
  'uk': 'uk',
  'nl': 'nl',
  'tr': 'tr',
  'sv': 'sv',
  'hi': 'hi',
  'ar': 'ar',
  'ja': 'ja',
  'ko': 'ko',
  'zh_Hans': 'zh-Hans',
  'hr': 'hr',
  'bs': 'bs',
  'sr_Latn': 'sr-Latn',
  'sr_Cyrl': 'sr-Cyrl',
};

void main() {
  final l10nDir = Directory('lib/l10n');
  if (!l10nDir.existsSync()) {
    stderr.writeln('Run from the repo root.');
    exit(1);
  }

  final byLocale = <String, Map<String, dynamic>>{};
  for (final entry in _localeMap.entries) {
    final file = File('lib/l10n/app_${entry.key}.arb');
    if (!file.existsSync()) {
      stderr.writeln('  !! missing ${file.path}');
      continue;
    }
    byLocale[entry.value] =
        jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
  }

  _write(
    'ios/PlatrareWidgets/Localizable.xcstrings',
    _buildCatalog(byLocale, _widgetKeys, _literals),
  );
  // AppShortcuts must ship as legacy per-language .strings, not .xcstrings:
  // string catalogs for App Shortcuts require a deployment target of iOS 17,
  // and the app target still deploys to 13. (The widget extension is 17+, so
  // it can use the modern catalog above.)
  _writeAppShortcutsStrings(byLocale);
}

void _writeAppShortcutsStrings(Map<String, Map<String, dynamic>> byLocale) {
  var written = 0;
  byLocale.forEach((lang, arb) {
    final lines = <String>[
      '/* Generated by tool/gen_ios_widget_strings.dart — do not edit. */',
    ];
    _phraseKeys.forEach((englishPhrase, arbKey) {
      final value = arb[arbKey] as String?;
      if (value == null) return;
      final localized = value.replaceAll('{appName}', r'${applicationName}');
      lines.add('"${_esc(englishPhrase)}" = "${_esc(localized)}";');
    });
    if (lines.length == 1) return;

    final dir = Directory('ios/Runner/$lang.lproj');
    dir.createSync(recursive: true);
    File('${dir.path}/AppShortcuts.strings')
        .writeAsStringSync('${lines.join('\n')}\n');
    written++;
  });
  stdout.writeln('  ios/Runner/*.lproj/AppShortcuts.strings  ($written locales)');
}

String _esc(String s) => s.replaceAll(r'\', r'\\').replaceAll('"', r'\"');

Map<String, dynamic> _buildCatalog(
  Map<String, Map<String, dynamic>> byLocale,
  Map<String, String> keys,
  Map<String, Map<String, String>> literals, {
  bool substituteAppName = false,
}) {
  final strings = <String, dynamic>{};

  keys.forEach((catalogKey, arbKey) {
    final localizations = <String, dynamic>{};
    byLocale.forEach((lang, arb) {
      var value = arb[arbKey] as String?;
      if (value == null) return;
      if (substituteAppName) {
        value = value.replaceAll('{appName}', r'${applicationName}');
      }
      localizations[lang] = {
        'stringUnit': {'state': 'translated', 'value': value},
      };
    });
    if (localizations.isEmpty) return;
    strings[catalogKey] = {
      'extractionState': 'manual',
      'localizations': localizations,
    };
  });

  literals.forEach((catalogKey, perLocale) {
    final fallback = perLocale['*'];
    final localizations = <String, dynamic>{};
    for (final lang in byLocale.keys) {
      final value = perLocale[lang] ?? fallback;
      if (value == null) continue;
      localizations[lang] = {
        'stringUnit': {'state': 'translated', 'value': value},
      };
    }
    strings[catalogKey] = {
      'extractionState': 'manual',
      'localizations': localizations,
    };
  });

  return {
    'sourceLanguage': 'en',
    'version': '1.0',
    'strings': strings,
  };
}

void _write(String path, Map<String, dynamic> catalog) {
  final file = File(path);
  file.parent.createSync(recursive: true);
  file.writeAsStringSync(
      '${const JsonEncoder.withIndent('  ').convert(catalog)}\n');
  final count = (catalog['strings'] as Map).length;
  stdout.writeln('  $path  ($count keys)');
}
